[build]
builder = "heroku/builder:24"

[deploy]
startCommand = "java -Xmx256m -Xms128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -XX:+UseCompressedOops -XX:+UseCompressedClassPointers -jar target/homework3-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"

[[services]]
name = "web"

[services.variables]
JAVA_OPTS = "-Xmx256m -Xms128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -XX:+UseCompressedOops -XX:+UseCompressedClassPointers"
